name: Deploy

on:
  workflow_run:
    workflows: ['Run Tests']
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Run redeployment script
        run: ssh vps 'cd ${{ secrets.PROJECT_ROOT }} && ./redeploy-site.sh'

      - name: Print container status
        run: docker compose -f docker-compose.prod.yml ps

      - name: Send Discord message
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Deployment Successful"
