name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    env:
      - TESTING: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.21"

      - name: Setup Python virtual environment
        run: python -m venv python3-virtualenv

      - name: Install dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Run tests
        run: ./run_test.sh
